version: '3.7'
services:
  client:
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    image: waves_client
    container_name: waves_client_container
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - waves_network
    restart: always
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    image: ishantgupta777/waves_server
    container_name: waves_server_container
    restart: always
    command: npm run server
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/waves2020
    networks:
      - waves_network 
  mongo:
    image: mongo
    restart: always
    container_name: waves_mongo_container
    ports:
      - '27017:27017'
    networks:
      - waves_network
    volumes:
      - data_mongo:/data/db

  # nginx_service:
  #   image: waves_nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - client
  #     - api

networks:
  waves_network:
      driver: bridge
    
volumes:
    data_mongo:
    node_modules:
    web-root:
      driver: local